name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_TOKEN }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update summary cards"